---
token:
  description: "GitHub oAuth Token"
  type: "string"
  default: "{{system.github_oauth_token}}"
  required: true

user:
  description: "GitHub Username"
  type: "string"

password:
  description: "GitHub Password"
  type: "string"

github_type:
  description: "Default to either github or enterprise."
  type: "string"
  default: "online"
  enum:
    - "online"
    - "enterprise"
  required: true

base_url:
  description: "The GitHub URL, for GitHub Enterprise please set enterprise_url."
  type: "string"
  default: "https://api.github.com"
  required: true

enterprise_url:
  description: "GitHub API url (including /api/v3) of your GitHub Enterprise hostname."
  type: "string"

deployment_environment:
  description: "The environment for this StackStorm server."
  type: "string"
  required: true
  default: "production"

repository_sensor:
  description: "Sensor specific settings."
  type: "object"
  required: false
  additionalProperties: false
  properties:
    event_type_whitelist:
      type: "array"
      description: "Event types to watch for, e.g. IssuesEvent, PushEvent"
      items:
        type: "string"
      required: false
      default:
        - "IssuesEvent"
        - "IssueCommentEvent"
        - "ForkEvent"
        - "WatchEvent"
        - "ReleaseEvent"
        - "PushEvent"
    repositories:
      description: "Repositories to monitor"
      type: "array"
      required: true
      items:
        type: "object"
        required: true
        properties:
          user:
            description: "GitHub user or organization name"
            type: "string"
            required: true
          name:
            description: "Repository name"
            type: "string"
            required: true
    count:
      type: "integer"
      description: "Maximum number of old events to retrieve"
      required: false
      default: 30
