---
token:
  description: "GitHub oAuth Token"
  type: "string"
  default: "{{ st2kv.system.github_oauth_token }}"
  required: true
  secret: true

user:
  description: "GitHub Username"
  type: "string"

password:
  description: "GitHub Password"
  type: "string"
  secret: true

github_type:
  description: "Default to either github or enterprise."
  type: "string"
  default: "online"
  enum:
    - "online"
    - "enterprise"
  required: true

web_url:
  description: "The GitHub URL."
  type: "string"
  default: "https://github.example.com"
  required: false

base_url:
  description: "GitHub API url, include /api/v3 for GitHub Enterprise. exp: "
  type: "string"
  default: "https://github.example.com/api/v3"
  required: false

deployment_environment:
  description: "The environment for this StackStorm server."
  type: "string"
  required: true
  default: "production"

repository_sensor:
  description: "Sensor specific settings, with default github type."
  type: "object"
  required: false
  additionalProperties: false
  properties:
    event_type_whitelist:
      type: "array"
      description: "Event types to watch for, e.g. IssuesEvent, PushEvent"
      items:
        type: "string"
      required: false
      default:
        - "IssuesEvent"
        - "IssueCommentEvent"
        - "ForkEvent"
        - "WatchEvent"
        - "ReleaseEvent"
        - "PushEvent"
    repositories:
      description: "Repositories to monitor"
      type: "array"
      required: true
      items:
        type: "object"
        required: true
        properties:
          user:
            description: "GitHub user or organization name"
            type: "string"
            required: true
          name:
            description: "Repository name"
            type: "string"
            required: true
    count:
      type: "integer"
      description: "Maximum number of old events to retrieve"
      required: false
      default: 30
